/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class Account extends SpeakeasyBase {
    /**
     * List of the users in the account
     */
    @SpeakeasyMetadata()
    accountUsers: string[];

    /**
     * Timestamp of the account creation date
     */
    @SpeakeasyMetadata()
    createdAt: string;

    /**
     * The id of the account
     */
    @SpeakeasyMetadata()
    id: number;

    /**
     * The name of the account
     */
    @SpeakeasyMetadata()
    name: string;

    /**
     * The id of the account owner
     */
    @SpeakeasyMetadata()
    ownerId: number;

    /**
     * If the account is personal or belonging to another account
     */
    @SpeakeasyMetadata()
    personal: boolean;

    /**
     * Timestamp of the last account update date
     */
    @SpeakeasyMetadata()
    updatedAt: string;
}
