/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class EnrichCompanyRequest extends SpeakeasyBase {
  /**
   * Country code of the company
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=country_code",
  })
  countryCode?: string;

  /**
   * The headquarters of the company
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=headquarters",
  })
  headquarters?: string;

  /**
   * ID of the company
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=id" })
  id?: string;

  /**
   * Game of the company
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=name" })
  name?: string;
}

export class EnrichCompanyResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  body?: Uint8Array;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
