/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class SearchCompaniesApplicationJSON extends SpeakeasyBase {
    /**
     * Filter for searching
     */
    @SpeakeasyMetadata()
    @Expose({ name: "filter" })
    filter?: string;

    /**
     * Number of results per page (0-100) default 10
     */
    @SpeakeasyMetadata()
    @Expose({ name: "limit" })
    limit?: string;

    /**
     * The offset number to start at
     */
    @SpeakeasyMetadata()
    @Expose({ name: "page" })
    page?: string;

    /**
     * Query for searching
     */
    @SpeakeasyMetadata()
    @Expose({ name: "query" })
    query?: string;
}

export class SearchCompaniesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
